### ISSUE TITLE
Numbers spam in chat when mining ores

### ISSUE THREAD

**Issue by corexti** [KuCZik/CoalDiamonds#1]
When mining coal ores, some random numbers show up in chat for each ore.
Example: 100 37 3 3

**Comment by corexti** [comment]
My mistake, was using wrong version. It's fixed in newest one.

**Comment by KuCZik** [comment]
Yeah someone told me this on Spigot, it was my debug code that I forgot to remove before release. Sorry about that, should be fixed in 1.2.1.

Bug removed in commit https://github.com/KuCZik/CoalDiamonds/commit/bf1fdbee6c54c8863a9f41e47ff49953f15080c2

Locking thread.
